export default [
  { _id: "M101", name: "Introduction to Rocket Propulsion", course: "RS101", lessons: [{ _id: "L101", name: "Propulsion basics" }, { _id: "L102", name: "Momentum & thrust" }] },
  { _id: "M102", name: "History of Rocketry", course: "RS101", lessons: [{ _id: "L103", name: "Early rocketry" }, { _id: "L104", name: "Modern launch systems" }] },
  { _id: "M103", name: "Rocket Engine Types", course: "RS101", lessons: [{ _id: "L105", name: "Liquid engines" }, { _id: "L106", name: "Solid engines" }] },
  { _id: "M201", name: "Airflow Fundamentals", course: "RS102", lessons: [{ _id: "L201", name: "Flow properties" }, { _id: "L202", name: "Reynolds number" }] },
  { _id: "M202", name: "Lift and Drag", course: "RS102", lessons: [{ _id: "L203", name: "Lift equation" }, { _id: "L204", name: "Drag components" }] },
  { _id: "M203", name: "Airfoils and Wings", course: "RS102", lessons: [{ _id: "L205", name: "Airfoil shapes" }, { _id: "L206", name: "Stall" }] },
  { _id: "M301", name: "Spacecraft Systems Overview", course: "RS103", lessons: [{ _id: "L301", name: "Subsystems" }, { _id: "L302", name: "Design tradeoffs" }] },
  { _id: "M302", name: "Power and Thermal", course: "RS103", lessons: [{ _id: "L303", name: "Power sources" }, { _id: "L304", name: "Thermal control" }] },
  { _id: "M303", name: "Payload Integration", course: "RS103", lessons: [{ _id: "L305", name: "Payload types" }, { _id: "L306", name: "Integration process" }] },
  { _id: "M401", name: "Organic Structures", course: "RS104", lessons: [{ _id: "L401", name: "Functional groups" }, { _id: "L402", name: "Stereochemistry" }] },
  { _id: "M402", name: "Reactions and Mechanisms", course: "RS104", lessons: [{ _id: "L403", name: "Reaction types" }, { _id: "L404", name: "Mechanism notation" }] },
  { _id: "M501", name: "Coordination Chemistry", course: "RS105", lessons: [{ _id: "L501", name: "Metal complexes" }, { _id: "L502", name: "Bonding theories" }] },
  { _id: "M502", name: "Symmetry and Crystal Field", course: "RS105", lessons: [{ _id: "L503", name: "Point groups" }, { _id: "L504", name: "Crystal field theory" }] },
  { _id: "M601", name: "Thermodynamics", course: "RS106", lessons: [{ _id: "L601", name: "Laws of thermodynamics" }, { _id: "L602", name: "Entropy" }] },
  { _id: "M602", name: "Quantum Mechanics", course: "RS106", lessons: [{ _id: "L603", name: "Wave functions" }, { _id: "L604", name: "Operators" }] },
  { _id: "M701", name: "Elvish Languages", course: "RS107", lessons: [{ _id: "L701", name: "Sindarin basics" }, { _id: "L702", name: "Quenya script" }] },
  { _id: "M702", name: "Dwarvish and Black Speech", course: "RS107", lessons: [{ _id: "L703", name: "Khuzdul phonology" }, { _id: "L704", name: "The Black Speech" }] },
  { _id: "M801", name: "Elves and Men Relations", course: "RS108", lessons: [{ _id: "L801", name: "Historical alliances" }, { _id: "L802", name: "Council of Elrond" }] },
  { _id: "M802", name: "Wizard Diplomacy", course: "RS108", lessons: [{ _id: "L803", name: "Role of Istari" }, { _id: "L804", name: "War of the Ring" }] },
];
